title: Uroš Bojanić
logo: "/images/uros.jpeg?raw=true"
description: >
  <a href="mailto:bu190077d@student.etf.bg.ac.rs"><i class="fa fa-envelope"></i> bu190077d@student.etf.bg.ac.rs</a>
  <br><br>
  Welcome to my portfolio website!👋
  <br><br>
  Read more about my <a href="#portfolio">background</a>, <a href="#internships">experience</a>, and <a href="#projects">projects</a>. Also, feel free to reach out on social media!
  <br><br>
  <a href="https://www.linkedin.com/in/uros-bojanic/"><i class="fa fa-linkedin"></i> Visit My LinkedIn Profile</a>
  <br>
  <a href="https://github.com/uros-bojanic/"><i class="fa fa-github-square"></i> Visit My GitHub Profile</a>
  <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
